### ISSUE TITLE
FontAwesome 5 compatibility

### ISSUE THREAD

**Issue by santiGoncalves** [laistomazz/font-awesome-picker#1]
You have this on mind? it would be really helpfull to the project that im developing, thanks

**Comment by laistomazz** [comment]
I'm going to look into the new version and I'll let you know, ok? Thanks

**Comment by santiGoncalves** [comment]
Great :) thanks!!

**Comment by riksnelders** [comment]
Any update on this? Using FA 5 pro

**Comment by laistomazz** [comment]
@santiGoncalves @riksnelders I just published a version 2 to support it. Please read the docs and if you have any issues, let me know.

**Comment by santiGoncalves** [comment]
Hi? just tried to check it out but it's not showing any icon at the list,  Using FA 5 pro

**Comment by laistomazz** [comment]
Hi @santiGoncalves 

How are you loading FA?

**Comment by santiGoncalves** [comment]
With webpack

**Comment by santiGoncalves** [comment]
Tell me if you need help with anything :)

**Comment by riksnelders** [comment]
You could just load the JSON from FA :)? and bind them to FA versions ?
Anyway, fixed my own picker!
